# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72611b0a437dbc820b785fbf600954263faf81c13f8433c84451ac12f323a8534b0a35ab5f905301f02ae74e997e793f95d92e2c486737951ccecd0e543a907e

test:
  secret_key_base: c9a7ca30cb01a716e99fff9353c9dafedb328d7c40d68650a7fd995c495e4f73d73c60e526205065f5e1ca3561fbf6722b81733c3ef314b437cc865b778ddafd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
